// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id]').default>>>>
    }
    '/api/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index').default>>>>
    }
    '/api/questions/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/[id]').default>>>>
    }
    '/api/questions/export': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/export').default>>>>
    }
    '/api/questions/import': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/import').default>>>>
    }
    '/api/questions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/index').default>>>>
    }
    '/api/statistics': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/statistics/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}