/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$User$creatorId,
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$User$updaterId,
                }, username: {
                    name: "username",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, roles: {
                    name: "roles",
                    type: "Role",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'users',
                }, createdRoles: {
                    name: "createdRoles",
                    type: "Role",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedRoles: {
                    name: "updatedRoles",
                    type: "Role",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdPermissions: {
                    name: "createdPermissions",
                    type: "Permission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedPermissions: {
                    name: "updatedPermissions",
                    type: "Permission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdCategories: {
                    name: "createdCategories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedCategories: {
                    name: "updatedCategories",
                    type: "Category",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdSubjects: {
                    name: "createdSubjects",
                    type: "Subject",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedSubjects: {
                    name: "updatedSubjects",
                    type: "Subject",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdGrades: {
                    name: "createdGrades",
                    type: "Grade",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedGrades: {
                    name: "updatedGrades",
                    type: "Grade",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdSources: {
                    name: "createdSources",
                    type: "Source",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedSources: {
                    name: "updatedSources",
                    type: "Source",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdQuestions: {
                    name: "createdQuestions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedQuestions: {
                    name: "updatedQuestions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, createdTags: {
                    name: "createdTags",
                    type: "Tag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedTags: {
                    name: "updatedTags",
                    type: "Tag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                }, systemLogs: {
                    name: "systemLogs",
                    type: "SystemLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, createdTagCategories: {
                    name: "createdTagCategories",
                    type: "TagCategory",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'createdBy',
                }, updatedTagCategories: {
                    name: "updatedTagCategories",
                    type: "TagCategory",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'updatedBy',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, username: {
                    name: "username",
                    fields: ["username"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            }
            ,
        }
        ,
        role: {
            name: 'Role', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Role$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Role$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, users: {
                    name: "users",
                    type: "User",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'roles',
                }, permissions: {
                    name: "permissions",
                    type: "Permission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'roles',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdRoles',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedRoles',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            }
            ,
        }
        ,
        permission: {
            name: 'Permission', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Permission$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Permission$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, groupName: {
                    name: "groupName",
                    type: "String",
                }, groupCode: {
                    name: "groupCode",
                    type: "String",
                }, actionName: {
                    name: "actionName",
                    type: "String",
                }, actionCode: {
                    name: "actionCode",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, roles: {
                    name: "roles",
                    type: "Role",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'permissions',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdPermissions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedPermissions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                }, groupCode_actionCode: {
                    name: "groupCode_actionCode",
                    fields: ["groupCode", "actionCode"]
                },
            }
            ,
        }
        ,
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Category$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Category$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, questions: {
                    name: "questions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdCategories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedCategories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        subject: {
            name: 'Subject', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Subject$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Subject$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, questions: {
                    name: "questions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'subject',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdSubjects',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedSubjects',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        grade: {
            name: 'Grade', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Grade$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Grade$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, questions: {
                    name: "questions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'grade',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdGrades',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedGrades',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        source: {
            name: 'Source', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Source$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Source$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, type: {
                    name: "type",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, questions: {
                    name: "questions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'source',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdSources',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedSources',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        tagCategory: {
            name: 'TagCategory', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$TagCategory$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$TagCategory$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, allowMultiple: {
                    name: "allowMultiple",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, tags: {
                    name: "tags",
                    type: "Tag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdTagCategories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedTagCategories',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            }
            ,
        }
        ,
        tag: {
            name: 'Tag', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Tag$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Tag$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, name: {
                    name: "name",
                    type: "String",
                }, code: {
                    name: "code",
                    type: "String",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, sortOrder: {
                    name: "sortOrder",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, category: {
                    name: "category",
                    type: "TagCategory",
                    isDataModel: true,
                    backLink: 'tags',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, questions: {
                    name: "questions",
                    type: "Question",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'tags',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdTags',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedTags',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, categoryId_name: {
                    name: "categoryId_name",
                    fields: ["categoryId", "name"]
                },
            }
            ,
        }
        ,
        question: {
            name: 'Question', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Question$creatorId,
                    isForeignKey: true,
                    relationField: 'createdBy',
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$Question$updaterId,
                    isForeignKey: true,
                    relationField: 'updatedBy',
                }, title: {
                    name: "title",
                    type: "String",
                }, content: {
                    name: "content",
                    type: "String",
                }, answer: {
                    name: "answer",
                    type: "String",
                    isOptional: true,
                }, analysis: {
                    name: "analysis",
                    type: "String",
                    isOptional: true,
                }, difficulty: {
                    name: "difficulty",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 1 }] }],
                }, status: {
                    name: "status",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "value": "DRAFT" }] }],
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, subjectId: {
                    name: "subjectId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'subject',
                }, gradeId: {
                    name: "gradeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'grade',
                }, sourceId: {
                    name: "sourceId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'source',
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'questions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, subject: {
                    name: "subject",
                    type: "Subject",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'questions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "subjectId" },
                }, grade: {
                    name: "grade",
                    type: "Grade",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'questions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "gradeId" },
                }, source: {
                    name: "source",
                    type: "Source",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'questions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "sourceId" },
                }, tags: {
                    name: "tags",
                    type: "Tag",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'questions',
                }, createdBy: {
                    name: "createdBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'createdQuestions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "creatorId" },
                }, updatedBy: {
                    name: "updatedBy",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'updatedQuestions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "updaterId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        systemLog: {
            name: 'SystemLog', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, isDeleted: {
                    name: "isDeleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, creatorId: {
                    name: "creatorId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$SystemLog$creatorId,
                }, updaterId: {
                    name: "updaterId",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [] }],
                    defaultValueProvider: $default$SystemLog$updaterId,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, module: {
                    name: "module",
                    type: "String",
                }, action: {
                    name: "action",
                    type: "String",
                }, target: {
                    name: "target",
                    type: "String",
                }, targetId: {
                    name: "targetId",
                    type: "String",
                }, detail: {
                    name: "detail",
                    type: "String",
                    isOptional: true,
                }, ip: {
                    name: "ip",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'systemLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
    }
    ,
    authModel: 'User'
};
function $default$User$creatorId(user: any): unknown {
    return user?.id;
}

function $default$User$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Role$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Role$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Permission$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Permission$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Category$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Category$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Subject$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Subject$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Grade$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Grade$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Source$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Source$updaterId(user: any): unknown {
    return user?.id;
}

function $default$TagCategory$creatorId(user: any): unknown {
    return user?.id;
}

function $default$TagCategory$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Tag$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Tag$updaterId(user: any): unknown {
    return user?.id;
}

function $default$Question$creatorId(user: any): unknown {
    return user?.id;
}

function $default$Question$updaterId(user: any): unknown {
    return user?.id;
}

function $default$SystemLog$creatorId(user: any): unknown {
    return user?.id;
}

function $default$SystemLog$updaterId(user: any): unknown {
    return user?.id;
}
export default metadata;
