/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export * from './user';
export * from './role';
export * from './permission';
export * from './category';
export * from './subject';
export * from './grade';
export * from './source';
export * from './tag-category';
export * from './tag';
export * from './question';
export * from './system-log';
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5';
export { VueQueryContextKey, provideHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
export { default as metadata } from './__model_meta';
