/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Permission } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreatePermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionCreateArgs, DefaultError, Permission, true>('Permission', 'POST', `${endpoint}/permission/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyPermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Permission', 'POST', `${endpoint}/permission/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyPermission<TArgs extends Prisma.PermissionFindManyArgs, TQueryFnData = Array<Prisma.PermissionGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPermission<TArgs extends Prisma.PermissionFindManyArgs, TQueryFnData = Array<Prisma.PermissionGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/findMany`, args, options, fetch);
}

export function useFindUniquePermission<TArgs extends Prisma.PermissionFindUniqueArgs, TQueryFnData = Prisma.PermissionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/findUnique`, args, options, fetch);
}

export function useFindFirstPermission<TArgs extends Prisma.PermissionFindFirstArgs, TQueryFnData = Prisma.PermissionGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/findFirst`, args, options, fetch);
}

export function useUpdatePermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionUpdateArgs, DefaultError, Permission, true>('Permission', 'PUT', `${endpoint}/permission/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyPermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Permission', 'PUT', `${endpoint}/permission/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertPermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionUpsertArgs, DefaultError, Permission, true>('Permission', 'POST', `${endpoint}/permission/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletePermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Permission | undefined), DefaultError, Prisma.PermissionDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionDeleteArgs, DefaultError, Permission, true>('Permission', 'DELETE', `${endpoint}/permission/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PermissionDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Permission, Prisma.PermissionGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyPermission(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PermissionDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PermissionDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Permission', 'DELETE', `${endpoint}/permission/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PermissionDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PermissionDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PermissionDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregatePermission<TArgs extends Prisma.PermissionAggregateArgs, TQueryFnData = Prisma.GetPermissionAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/aggregate`, args, options, fetch);
}

export function useGroupByPermission<TArgs extends Prisma.PermissionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PermissionGroupByArgs['orderBy'] } : { orderBy?: Prisma.PermissionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PermissionGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.PermissionGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.PermissionGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PermissionGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PermissionGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PermissionGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/groupBy`, args, options, fetch);
}

export function useCountPermission<TArgs extends Prisma.PermissionCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PermissionCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PermissionCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PermissionCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Permission', `${endpoint}/permission/count`, args, options, fetch);
}

export function useCheckPermission<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; isDeleted?: boolean; creatorId?: string; updaterId?: string; groupName?: string; groupCode?: string; actionName?: string; actionCode?: string; code?: string; description?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Permission', `${endpoint}/permission/check`, args, options, fetch);
}
