/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, SystemLog } from "@zenstackhq/runtime/models";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateSystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogCreateArgs, DefaultError, SystemLog, true>('SystemLog', 'POST', `${endpoint}/systemLog/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManySystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('SystemLog', 'POST', `${endpoint}/systemLog/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManySystemLog<TArgs extends Prisma.SystemLogFindManyArgs, TQueryFnData = Array<Prisma.SystemLogGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/findMany`, args, options, fetch);
}

export function useInfiniteFindManySystemLog<TArgs extends Prisma.SystemLogFindManyArgs, TQueryFnData = Array<Prisma.SystemLogGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/findMany`, args, options, fetch);
}

export function useFindUniqueSystemLog<TArgs extends Prisma.SystemLogFindUniqueArgs, TQueryFnData = Prisma.SystemLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/findUnique`, args, options, fetch);
}

export function useFindFirstSystemLog<TArgs extends Prisma.SystemLogFindFirstArgs, TQueryFnData = Prisma.SystemLogGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/findFirst`, args, options, fetch);
}

export function useUpdateSystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogUpdateArgs, DefaultError, SystemLog, true>('SystemLog', 'PUT', `${endpoint}/systemLog/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManySystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('SystemLog', 'PUT', `${endpoint}/systemLog/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertSystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogUpsertArgs, DefaultError, SystemLog, true>('SystemLog', 'POST', `${endpoint}/systemLog/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteSystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(SystemLog | undefined), DefaultError, Prisma.SystemLogDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogDeleteArgs, DefaultError, SystemLog, true>('SystemLog', 'DELETE', `${endpoint}/systemLog/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, SystemLog, Prisma.SystemLogGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManySystemLog(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SystemLogDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.SystemLogDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('SystemLog', 'DELETE', `${endpoint}/systemLog/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.SystemLogDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.SystemLogDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.SystemLogDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateSystemLog<TArgs extends Prisma.SystemLogAggregateArgs, TQueryFnData = Prisma.GetSystemLogAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/aggregate`, args, options, fetch);
}

export function useGroupBySystemLog<TArgs extends Prisma.SystemLogGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SystemLogGroupByArgs['orderBy'] } : { orderBy?: Prisma.SystemLogGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.SystemLogGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.SystemLogGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.SystemLogGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.SystemLogGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SystemLogGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.SystemLogGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/groupBy`, args, options, fetch);
}

export function useCountSystemLog<TArgs extends Prisma.SystemLogCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.SystemLogCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SystemLogCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SystemLogCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('SystemLog', `${endpoint}/systemLog/count`, args, options, fetch);
}

export function useCheckSystemLog<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; isDeleted?: boolean; creatorId?: string; updaterId?: string; userId?: string; module?: string; action?: string; target?: string; targetId?: string; detail?: string; ip?: string; userAgent?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('SystemLog', `${endpoint}/systemLog/check`, args, options, fetch);
}
