// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/11/25 22:27:00
const configMerger = require("Z:/labs/windsurf/CascadeProjects/windsurf-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["Z:/labs/windsurf/CascadeProjects/windsurf-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/plugins/**/*.{js,ts,mjs}","Z:/labs/windsurf/CascadeProjects/windsurf-project/composables/**/*.{js,ts,mjs}","Z:/labs/windsurf/CascadeProjects/windsurf-project/utils/**/*.{js,ts,mjs}","Z:/labs/windsurf/CascadeProjects/windsurf-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","Z:/labs/windsurf/CascadeProjects/windsurf-project/app.config.{js,ts,mjs}"] } }));

module.exports = config
